/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as SourcesRouteImport } from './routes/sources'
import { Route as SheetSyncsRouteImport } from './routes/sheet-syncs'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OfficesRouteImport } from './routes/offices'
import { Route as MyTeamRouteImport } from './routes/my-team'
import { Route as MyOfficeRouteImport } from './routes/my-office'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as IpWhitelistRouteImport } from './routes/ip-whitelist'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ApiLogsRouteImport } from './routes/api-logs'
import { Route as ApiKeysRouteImport } from './routes/api-keys'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeadsIndexRouteImport } from './routes/leads.index'
import { Route as SettingsProfileRouteImport } from './routes/settings.profile'
import { Route as SettingsPasswordRouteImport } from './routes/settings.password'
import { Route as SettingsLanguageRouteImport } from './routes/settings.language'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as LeadsIdRouteImport } from './routes/leads.$id'
import { Route as AdminPermissionsRouteImport } from './routes/admin.permissions'
import { Route as ApiPublicSheetsSyncRouteImport } from './routes/api/public/sheets/sync'
import { Route as ApiPublicLeadsListRouteImport } from './routes/api/public/leads/list'
import { Route as ApiPublicLeadsIngestRouteImport } from './routes/api/public/leads/ingest'
import { Route as ApiPublicContactRequestsIngestRouteImport } from './routes/api/public/contact-requests/ingest'
import { Route as ApiPublicAffiliateLeadsIngestRouteImport } from './routes/api/public/affiliate/leads/ingest'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesRoute = SourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => rootRouteImport,
} as any)
const SheetSyncsRoute = SheetSyncsRouteImport.update({
  id: '/sheet-syncs',
  path: '/sheet-syncs',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficesRoute = OfficesRouteImport.update({
  id: '/offices',
  path: '/offices',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTeamRoute = MyTeamRouteImport.update({
  id: '/my-team',
  path: '/my-team',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOfficeRoute = MyOfficeRouteImport.update({
  id: '/my-office',
  path: '/my-office',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const IpWhitelistRoute = IpWhitelistRouteImport.update({
  id: '/ip-whitelist',
  path: '/ip-whitelist',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogsRoute = ApiLogsRouteImport.update({
  id: '/api-logs',
  path: '/api-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api-keys',
  path: '/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsIndexRoute = LeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LeadsRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsPasswordRoute = SettingsPasswordRouteImport.update({
  id: '/password',
  path: '/password',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsLanguageRoute = SettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const LeadsIdRoute = LeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LeadsRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/admin/permissions',
  path: '/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSheetsSyncRoute = ApiPublicSheetsSyncRouteImport.update({
  id: '/api/public/sheets/sync',
  path: '/api/public/sheets/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsListRoute = ApiPublicLeadsListRouteImport.update({
  id: '/api/public/leads/list',
  path: '/api/public/leads/list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLeadsIngestRoute = ApiPublicLeadsIngestRouteImport.update({
  id: '/api/public/leads/ingest',
  path: '/api/public/leads/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRequestsIngestRoute =
  ApiPublicContactRequestsIngestRouteImport.update({
    id: '/api/public/contact-requests/ingest',
    path: '/api/public/contact-requests/ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAffiliateLeadsIngestRoute =
  ApiPublicAffiliateLeadsIngestRouteImport.update({
    id: '/api/public/affiliate/leads/ingest',
    path: '/api/public/affiliate/leads/ingest',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/api-keys': typeof ApiKeysRoute
  '/api-logs': typeof ApiLogsRoute
  '/calendar': typeof CalendarRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/ip-whitelist': typeof IpWhitelistRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-office': typeof MyOfficeRoute
  '/my-team': typeof MyTeamRoute
  '/offices': typeof OfficesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sheet-syncs': typeof SheetSyncsRoute
  '/sources': typeof SourcesRoute
  '/users': typeof UsersRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/leads/$id': typeof LeadsIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/public/contact-requests/ingest': typeof ApiPublicContactRequestsIngestRoute
  '/api/public/leads/ingest': typeof ApiPublicLeadsIngestRoute
  '/api/public/leads/list': typeof ApiPublicLeadsListRoute
  '/api/public/sheets/sync': typeof ApiPublicSheetsSyncRoute
  '/api/public/affiliate/leads/ingest': typeof ApiPublicAffiliateLeadsIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/api-keys': typeof ApiKeysRoute
  '/api-logs': typeof ApiLogsRoute
  '/calendar': typeof CalendarRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/ip-whitelist': typeof IpWhitelistRoute
  '/login': typeof LoginRoute
  '/my-office': typeof MyOfficeRoute
  '/my-team': typeof MyTeamRoute
  '/offices': typeof OfficesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sheet-syncs': typeof SheetSyncsRoute
  '/sources': typeof SourcesRoute
  '/users': typeof UsersRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/leads/$id': typeof LeadsIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/leads': typeof LeadsIndexRoute
  '/api/public/contact-requests/ingest': typeof ApiPublicContactRequestsIngestRoute
  '/api/public/leads/ingest': typeof ApiPublicLeadsIngestRoute
  '/api/public/leads/list': typeof ApiPublicLeadsListRoute
  '/api/public/sheets/sync': typeof ApiPublicSheetsSyncRoute
  '/api/public/affiliate/leads/ingest': typeof ApiPublicAffiliateLeadsIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/affiliates': typeof AffiliatesRoute
  '/api-keys': typeof ApiKeysRoute
  '/api-logs': typeof ApiLogsRoute
  '/calendar': typeof CalendarRoute
  '/change-password': typeof ChangePasswordRoute
  '/dashboard': typeof DashboardRoute
  '/ip-whitelist': typeof IpWhitelistRoute
  '/leads': typeof LeadsRouteWithChildren
  '/login': typeof LoginRoute
  '/my-office': typeof MyOfficeRoute
  '/my-team': typeof MyTeamRoute
  '/offices': typeof OfficesRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sheet-syncs': typeof SheetSyncsRoute
  '/sources': typeof SourcesRoute
  '/users': typeof UsersRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/leads/$id': typeof LeadsIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/language': typeof SettingsLanguageRoute
  '/settings/password': typeof SettingsPasswordRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/leads/': typeof LeadsIndexRoute
  '/api/public/contact-requests/ingest': typeof ApiPublicContactRequestsIngestRoute
  '/api/public/leads/ingest': typeof ApiPublicLeadsIngestRoute
  '/api/public/leads/list': typeof ApiPublicLeadsListRoute
  '/api/public/sheets/sync': typeof ApiPublicSheetsSyncRoute
  '/api/public/affiliate/leads/ingest': typeof ApiPublicAffiliateLeadsIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/affiliates'
    | '/api-keys'
    | '/api-logs'
    | '/calendar'
    | '/change-password'
    | '/dashboard'
    | '/ip-whitelist'
    | '/leads'
    | '/login'
    | '/my-office'
    | '/my-team'
    | '/offices'
    | '/settings'
    | '/sheet-syncs'
    | '/sources'
    | '/users'
    | '/admin/permissions'
    | '/leads/$id'
    | '/settings/appearance'
    | '/settings/language'
    | '/settings/password'
    | '/settings/profile'
    | '/leads/'
    | '/api/public/contact-requests/ingest'
    | '/api/public/leads/ingest'
    | '/api/public/leads/list'
    | '/api/public/sheets/sync'
    | '/api/public/affiliate/leads/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/affiliates'
    | '/api-keys'
    | '/api-logs'
    | '/calendar'
    | '/change-password'
    | '/dashboard'
    | '/ip-whitelist'
    | '/login'
    | '/my-office'
    | '/my-team'
    | '/offices'
    | '/settings'
    | '/sheet-syncs'
    | '/sources'
    | '/users'
    | '/admin/permissions'
    | '/leads/$id'
    | '/settings/appearance'
    | '/settings/language'
    | '/settings/password'
    | '/settings/profile'
    | '/leads'
    | '/api/public/contact-requests/ingest'
    | '/api/public/leads/ingest'
    | '/api/public/leads/list'
    | '/api/public/sheets/sync'
    | '/api/public/affiliate/leads/ingest'
  id:
    | '__root__'
    | '/'
    | '/affiliates'
    | '/api-keys'
    | '/api-logs'
    | '/calendar'
    | '/change-password'
    | '/dashboard'
    | '/ip-whitelist'
    | '/leads'
    | '/login'
    | '/my-office'
    | '/my-team'
    | '/offices'
    | '/settings'
    | '/sheet-syncs'
    | '/sources'
    | '/users'
    | '/admin/permissions'
    | '/leads/$id'
    | '/settings/appearance'
    | '/settings/language'
    | '/settings/password'
    | '/settings/profile'
    | '/leads/'
    | '/api/public/contact-requests/ingest'
    | '/api/public/leads/ingest'
    | '/api/public/leads/list'
    | '/api/public/sheets/sync'
    | '/api/public/affiliate/leads/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AffiliatesRoute: typeof AffiliatesRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ApiLogsRoute: typeof ApiLogsRoute
  CalendarRoute: typeof CalendarRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  DashboardRoute: typeof DashboardRoute
  IpWhitelistRoute: typeof IpWhitelistRoute
  LeadsRoute: typeof LeadsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MyOfficeRoute: typeof MyOfficeRoute
  MyTeamRoute: typeof MyTeamRoute
  OfficesRoute: typeof OfficesRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SheetSyncsRoute: typeof SheetSyncsRoute
  SourcesRoute: typeof SourcesRoute
  UsersRoute: typeof UsersRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  ApiPublicContactRequestsIngestRoute: typeof ApiPublicContactRequestsIngestRoute
  ApiPublicLeadsIngestRoute: typeof ApiPublicLeadsIngestRoute
  ApiPublicLeadsListRoute: typeof ApiPublicLeadsListRoute
  ApiPublicSheetsSyncRoute: typeof ApiPublicSheetsSyncRoute
  ApiPublicAffiliateLeadsIngestRoute: typeof ApiPublicAffiliateLeadsIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources': {
      id: '/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof SourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sheet-syncs': {
      id: '/sheet-syncs'
      path: '/sheet-syncs'
      fullPath: '/sheet-syncs'
      preLoaderRoute: typeof SheetSyncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offices': {
      id: '/offices'
      path: '/offices'
      fullPath: '/offices'
      preLoaderRoute: typeof OfficesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-team': {
      id: '/my-team'
      path: '/my-team'
      fullPath: '/my-team'
      preLoaderRoute: typeof MyTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-office': {
      id: '/my-office'
      path: '/my-office'
      fullPath: '/my-office'
      preLoaderRoute: typeof MyOfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ip-whitelist': {
      id: '/ip-whitelist'
      path: '/ip-whitelist'
      fullPath: '/ip-whitelist'
      preLoaderRoute: typeof IpWhitelistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-logs': {
      id: '/api-logs'
      path: '/api-logs'
      fullPath: '/api-logs'
      preLoaderRoute: typeof ApiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-keys': {
      id: '/api-keys'
      path: '/api-keys'
      fullPath: '/api-keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads/': {
      id: '/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof LeadsIndexRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/password': {
      id: '/settings/password'
      path: '/password'
      fullPath: '/settings/password'
      preLoaderRoute: typeof SettingsPasswordRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/language': {
      id: '/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof SettingsLanguageRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/leads/$id': {
      id: '/leads/$id'
      path: '/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof LeadsIdRouteImport
      parentRoute: typeof LeadsRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sheets/sync': {
      id: '/api/public/sheets/sync'
      path: '/api/public/sheets/sync'
      fullPath: '/api/public/sheets/sync'
      preLoaderRoute: typeof ApiPublicSheetsSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/list': {
      id: '/api/public/leads/list'
      path: '/api/public/leads/list'
      fullPath: '/api/public/leads/list'
      preLoaderRoute: typeof ApiPublicLeadsListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/leads/ingest': {
      id: '/api/public/leads/ingest'
      path: '/api/public/leads/ingest'
      fullPath: '/api/public/leads/ingest'
      preLoaderRoute: typeof ApiPublicLeadsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact-requests/ingest': {
      id: '/api/public/contact-requests/ingest'
      path: '/api/public/contact-requests/ingest'
      fullPath: '/api/public/contact-requests/ingest'
      preLoaderRoute: typeof ApiPublicContactRequestsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/affiliate/leads/ingest': {
      id: '/api/public/affiliate/leads/ingest'
      path: '/api/public/affiliate/leads/ingest'
      fullPath: '/api/public/affiliate/leads/ingest'
      preLoaderRoute: typeof ApiPublicAffiliateLeadsIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LeadsRouteChildren {
  LeadsIdRoute: typeof LeadsIdRoute
  LeadsIndexRoute: typeof LeadsIndexRoute
}

const LeadsRouteChildren: LeadsRouteChildren = {
  LeadsIdRoute: LeadsIdRoute,
  LeadsIndexRoute: LeadsIndexRoute,
}

const LeadsRouteWithChildren = LeadsRoute._addFileChildren(LeadsRouteChildren)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsLanguageRoute: typeof SettingsLanguageRoute
  SettingsPasswordRoute: typeof SettingsPasswordRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsLanguageRoute: SettingsLanguageRoute,
  SettingsPasswordRoute: SettingsPasswordRoute,
  SettingsProfileRoute: SettingsProfileRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AffiliatesRoute: AffiliatesRoute,
  ApiKeysRoute: ApiKeysRoute,
  ApiLogsRoute: ApiLogsRoute,
  CalendarRoute: CalendarRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  DashboardRoute: DashboardRoute,
  IpWhitelistRoute: IpWhitelistRoute,
  LeadsRoute: LeadsRouteWithChildren,
  LoginRoute: LoginRoute,
  MyOfficeRoute: MyOfficeRoute,
  MyTeamRoute: MyTeamRoute,
  OfficesRoute: OfficesRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SheetSyncsRoute: SheetSyncsRoute,
  SourcesRoute: SourcesRoute,
  UsersRoute: UsersRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  ApiPublicContactRequestsIngestRoute: ApiPublicContactRequestsIngestRoute,
  ApiPublicLeadsIngestRoute: ApiPublicLeadsIngestRoute,
  ApiPublicLeadsListRoute: ApiPublicLeadsListRoute,
  ApiPublicSheetsSyncRoute: ApiPublicSheetsSyncRoute,
  ApiPublicAffiliateLeadsIngestRoute: ApiPublicAffiliateLeadsIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
