// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL ?? "https://ksavifrtljyolwqtcvcg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ?? import.meta.env.VITE_SUPABASE_ANON_KEY ?? "";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function getBrowserStorage() {
  if (typeof globalThis.window === "undefined") return null;
  try {
    return globalThis.window.localStorage ?? null;
  } catch {
    return null;
  }
}

// In-memory fallback storage so supabase-js never touches a bare `localStorage`
// reference during SSR (which would throw ReferenceError on the server).
const memoryStorage = (() => {
  const store = new Map<string, string>();
  return {
    getItem: (k: string) => (store.has(k) ? store.get(k)! : null),
    setItem: (k: string, v: string) => { store.set(k, v); },
    removeItem: (k: string) => { store.delete(k); },
  };
})();

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: getBrowserStorage() ?? memoryStorage,
    persistSession: !!getBrowserStorage(),
    autoRefreshToken: !!getBrowserStorage(),
    detectSessionInUrl: !!getBrowserStorage(),
  }
});